from typing import Dict, List

WALLS = ("#", "D")

colors = {
    "W": (255, 255, 255),  # White
    "O": (255, 88, 0),  # Orange
    "3": (255, 88, 0),
    "G": (0, 155, 72),  # Green
    "2": (0, 155, 72),
    "R": (183, 18, 52),  # Red
    "1": (183, 18, 52),
    "B": (0, 70, 173),  # Blue
    "0": (0, 70, 173),
    "Y": (255, 213, 0),  # Yellow
    "#": (25, 25, 25),  # Wall
    "C": (139, 0, 139),  # Control Buttons
    "D": (139, 69, 19),  # Door
    "P": (128, 128, 128),  # Pedestal
}

key_room_alt = [
    "#######",
    "#YYYDD#",
    "DYYYYYY",
    "DYYPYYY",
    "DYYYYYY",
    "#YYYDD#",
    "#######",
]

stickers: Dict[str, List[str]] = {
    "W0": [
        "##WWW##",
        "#WWWWW#",
        "WWWWWWW",
        "WWWWWWW",
        "WWWWWWW",
        "#WWWWW#",
        "##WWW##",
    ],
    "W1": [
        "#######",
        "#WWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "#WWWWW#",
        "#######",
    ],
    "W2": [
        "##WWW##",
        "#WWWWW#",
        "#WWWWW#",
        "#WWWWW#",
        "#WWWWW#",
        "#WWWWW#",
        "##WWW##",
    ],
    "W3": [
        "##WWW##",
        "#WWWWW#",
        "#WWWWWW",
        "#WWWWWW",
        "#WWWWWW",
        "#WWWWW#",
        "##WWW##",
    ],
    "W4": [
        "##WWW##",
        "#WW0WW#",
        "WWWWWWW",
        "W3WLW1W",
        "WWWWWWW",
        "#WW2WW#",
        "##WWW##",
    ],
    "W5": [
        "##WWW##",
        "#WWWWW#",
        "WWWWWWW",
        "WWWWWWW",
        "WWWWWWW",
        "#WWWWW#",
        "##WWW##",
    ],
    "W6": [
        "##WWW##",
        "#WWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "#WWWWW#",
        "#######",
    ],
    "W7": [
        "#######",
        "#WWWWW#",
        "#WWWWWW",
        "#WWWWWW",
        "#WWWWWW",
        "#WWWWW#",
        "##WWW##",
    ],
    "W8": [
        "##WWW##",
        "#WWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "WWWWWW#",
        "#WWWWW#",
        "#######",
    ],
    "O0": [
        "##OOO##",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "##OOO##",
    ],
    "O1": [
        "#######",
        "#OOOOO#",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOO#",
        "#######",
    ],
    "O2": [
        "##OOO##",
        "#OOOOO#",
        "OOOOOO#",
        "OOOOOO#",
        "OOOOOO#",
        "#OOOOO#",
        "##OOO##",
    ],
    "O3": [
        "##OOO##",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "##OOO##",
    ],
    "O4": [
        "#######",
        "#OOOOO#",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOO#",
        "##OOO##",
    ],
    "O5": [
        "##OOO##",
        "#OOOOO#",
        "OOOOOO#",
        "OOOOOO#",
        "OOOOOO#",
        "#OOOOO#",
        "#######",
    ],
    "O6": [
        "##OOO##",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#OOOOO#",
        "#######",
    ],
    "O7": [
        "##OOO##",
        "#OOOOO#",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOOO",
        "#OOOOO#",
        "#######",
    ],
    "O8": [
        "#######",
        "#OOOOO#",
        "OOOOOOO",
        "OOOOOOO",
        "OOOOOOO",
        "#OOOOO#",
        "#######",
    ],
    "G0": [
        "#######",
        "#GGGGG#",
        "#GGGGGG",
        "#GGGGGG",
        "#GGGGGG",
        "#GGGGG#",
        "#######",
    ],
    "G1": [
        "##GGG##",
        "#GGGGG#",
        "GGGGGGG",
        "GGGGGGG",
        "GGGGGGG",
        "#GGGGG#",
        "#######",
    ],
    "G2": [
        "#######",
        "#GGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "#GGGGG#",
        "#######",
    ],
    "G3": [
        "#######",
        "#GGGGG#",
        "#GGGGGG",
        "#GGGGGG",
        "#GGGGGG",
        "#GGGGG#",
        "##GGG##",
    ],
    "G4": [
        "#######",
        "#GGGGG#",
        "GGGGGGG",
        "GGGGGGG",
        "GGGGGGG",
        "#GGGGG#",
        "##GGG##",
    ],
    "G5": [
        "#######",
        "#GGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "#GGGGG#",
        "##GGG##",
    ],
    "G6": [
        "##GGG##",
        "#GGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "GGGGGG#",
        "#GGGGG#",
        "#######",
    ],
    "G7": [
        "##GGG##",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "#######",
    ],
    "G8": [
        "##GGG##",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "#GGGGG#",
        "##GGG##",
    ],
    "R0": [
        "#######",
        "#RRRRR#",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRR#",
        "##RRR##",
    ],
    "R1": [
        "##RRR##",
        "#RRRRR#",
        "RRRRRRR",
        "RRRRRRR",
        "RRRRRRR",
        "#RRRRR#",
        "#######",
    ],
    "R2": [
        "#######",
        "#RRRRR#",
        "RRRRRR#",
        "RRRRRR#",
        "RRRRRR#",
        "#RRRRR#",
        "#######",
    ],
    "R3": [
        "##RRR##",
        "#RRRRR#",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRR#",
        "#######",
    ],
    "R4": [
        "#######",
        "#RRRRR#",
        "RRRRRRR",
        "RRRRRRR",
        "RRRRRRR",
        "#RRRRR#",
        "#######",
    ],
    "R5": [
        "#######",
        "#RRRRR#",
        "RRRRRRR",
        "RRRRRRR",
        "RRRRRRR",
        "#RRRRR#",
        "#######",
    ],
    "R6": [
        "#######",
        "#RRRRR#",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRR#",
        "#######",
    ],
    "R7": [
        "#######",
        "#RRRRR#",
        "RRRRRR#",
        "RRRRRR#",
        "RRRRRR#",
        "#RRRRR#",
        "#######",
    ],
    "R8": [
        "#######",
        "#RRRRR#",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRRR",
        "#RRRRR#",
        "##RRR##",
    ],
    "B0": [
        "##BBB##",
        "#BBBBB#",
        "#BBBBBB",
        "#BBBBBB",
        "#BBBBBB",
        "#BBBBB#",
        "#######",
    ],
    "B1": [
        "#######",
        "#BBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "#BBBBB#",
        "##BBB##",
    ],
    "B2": [
        "##BBB##",
        "#BBBBB#",
        "#BBBBB#",
        "#BBBBB#",
        "#BBBBB#",
        "#BBBBB#",
        "#######",
    ],
    "B3": [
        "#######",
        "#BBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "#BBBBB#",
        "#######",
    ],
    "B4": [
        "##BBB##",
        "#BBBBB#",
        "#BBBBBB",
        "#BBBBBB",
        "#BBBBBB",
        "#BBBBB#",
        "#######",
    ],
    "B5": [
        "#######",
        "#BBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "#BBBBB#",
        "##BBB##",
    ],
    "B6": [
        "#######",
        "#BBBBB#",
        "BBBBBBB",
        "BBBBBBB",
        "BBBBBBB",
        "#BBBBB#",
        "#######",
    ],
    "B7": [
        "#######",
        "#BBBBB#",
        "BBBBBBB",
        "BBBBBBB",
        "BBBBBBB",
        "#BBBBB#",
        "#######",
    ],
    "B8": [
        "##BBB##",
        "#BBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "BBBBBB#",
        "#BBBBB#",
        "#######",
    ],
    "Y0": [
        "#######",
        "#YYYYY#",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYY#",
        "#######",
    ],
    "Y1": [
        "#######",
        "#YYYYY#",
        "YYYYYY#",
        "YYYYYY#",
        "YYYYYY#",
        "#YYYYY#",
        "#######",
    ],
    "Y2": [
        "##YYY##",
        "#YYYYY#",
        "#YYYYY#",
        "#YYYYY#",
        "#YYYYY#",
        "#YYYYY#",
        "##YYY##",
    ],
    "Y3": [
        "#######",
        "#YYYYY#",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYY#",
        "##YYY##",
    ],
    "Y4": [
        "#######",
        "#DDYYY#",
        "YYYYYYD",
        "YYYKYYD",
        "YYYYYYD",
        "#DDYYY#",
        "#######",
    ],
    "Y5": [
        "##YYY##",
        "#YYYYY#",
        "YYYYYY#",
        "YYYYYY#",
        "YYYYYY#",
        "#YYYYY#",
        "#######",
    ],
    "Y6": [
        "##YYY##",
        "#YYYYY#",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYYY",
        "#YYYYY#",
        "#######",
    ],
    "Y7": [
        "#######",
        "#YYYYY#",
        "YYYYYYY",
        "YYYYYYY",
        "YYYYYYY",
        "#YYYYY#",
        "#######",
    ],
    "Y8": [
        "#######",
        "#YYYYY#",
        "YYYYYYY",
        "YYYYYYY",
        "YYYYYYY",
        "#YYYYY#",
        "#######",
    ],
}
